### ISSUE TITLE
Installation failing on postinstall script (Node v10.0.0 and NPM 6.0)

### ISSUE THREAD

**Issue by manafount** [serverless/components#172]
Installing via npm with `npm i -g serverless-components` fails due to the dtrace-provider module failing to build.

It seems like there could be conflicting dependencies for dtrace-provider. I also did some digging that mentioned dtrace-provider possibly looking in the wrong global node_modules folder (possibly an nvm issue?).

In any case, it doesn't seem like a problem specifically with serverless-components, but I'm curious to see if anyone has run into this issue and might be able to shed some light on it.

Stack trace follows:

> node ./scripts/postinstall.js

npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
+ @serverless-components/eventgateway@0.1.0
added 12 packages from 11 contributors and updated 1 package in 55.13s

> dtrace-provider@0.6.0 install /Users/manafount/.nvm/versions/node/v10.0.0/lib/node_modules/serverless-components/registry/aws-dynamodb/node_modules/dtrace-provider
> node scripts/install.js

---------------░░░░⸩ ⠏ postinstall: sill install executeActions
Building dtrace-provider failed with exit code 1 and signal 0
re-run install with environment variable V set to see the build output
---------------░░░░⸩ ⠏ postinstall: sill install executeActions
+ @serverless-components/aws-dynamodb@1.0.0stall executeActions
added 47 packages from 108 contributors and updated 1 package in 62.828s
+ @serverless-components/aws-apigateway@0.1.0
added 16 packages from 70 contributors and updated 1 package in 64.346s
+ @serverless-components/s3-uploader@0.1.0
added 13 packages from 12 contributors and updated 1 package in 65.034s
+ @serverless-components/rest-api@0.1.0
added 1 package from 4 contributors and updated 1 package in 65.621s
+ @serverless/github-webhook-aws@0.1.0
updated 1 package in 65.717s
+ @serverless-components/s3-downloader@0.1.0
added 1 package from 5 contributors and updated 1 package in 66.089s
+ @serverless-components/aws-lambda@0.1.0
added 54 packages from 86 contributors and updated 1 package in 68.07s
+ @serverless-components/static-website@0.1.0
added 1 package from 4 contributors and updated 1 package in 68.408s
+ @serverless-components/mustache@0.1.0l install executeActions
added 12 packages from 9 contributors and updated 1 package in 69.391s
+ github-webhook@1.0.0
added 36 packages from 36 contributors and updated 1 package in 70.681s
+ serverless-components@0.1.2
updated 3 packages in 81.275s

**Comment by ebisbe** [comment]
@manafount I had today the same issue and for what I finally manage to see is related with Node itself. I have no clue what is really happening but I switched to node v8.11.1 and reinstalling the package and works again

**Comment by tatyree** [comment]
On OSX with node installed via homebrew (I'm betting versions don't matter, but mine are OSX 10.13.5 and node 10.6) this is an issue with these two node_modules:

`/usr/local/lib/node_modules/serverless-components/registry/aws-dynamodb/node_modules/dynamodb/dtrace-provider`

AND 

`/usr/local/lib/node_modules/serverless-components/registry/aws-dynamodb/node_modules/dynamodb/node_modules/bunyan/node_modules/dtrace-provider`

The write up on fixing it found at https://github.com/trentm/node-bunyan/issues/525 and https://github.com/nodejs/node-gyp/issues/569 are the twot I used to ultimately work through it.  Curiously, the `dynamodb/dtrace-provider` problem was fixed by nodejs/node-gyp/issues/569, while the `node_modules/bunyan` problem was fixed by trentm/node-bunyan/issues/525.  I say 'curiously' because they are both down to build errors with the `dtrace-provider` dependency and I would have expected a single fix to get them both.

**Comment by eahefnawy** [comment]
closing this as we've made a complete rewrite of the core and this issue no longer exists.

**Comment by zerozin-kang** [comment]
Did you fix this problem? I haven't been able to implement it for several days due to the same problem. I tested it on another computer, and it's all working fine.

**Comment by donghoon-song** [comment]
Still having the same issue on node 14.10.1 and npm 6.14.8, osx 10.15.6.
