### ISSUE TITLE
Role already exists -> deleted role -> policy AWSLambdaFullAccess does not exist or is not attachable

### ISSUE THREAD

**Issue by nectarcode** [serverless/components#918]
I'm using express@2.0.5

I haven't changed anything recently, but I'm no longer able to deploy to any stage

After I deleted the role it said `Role with name nectar-api-90yr4ln-lambda-role already exists.` so i deleted the role

Then i tried deploying and got the error `policy AWSLambdaFullAccess does not exist or is not attachable`

Then I tried deploying again and got the same `Role already exists` error

Fortunately my API is still up and running...but I've never run into this issue before...I may try `sls` remove on dev and see if that solves the issue.

**Comment by nectarcode** [comment]
I noticed that the name of the policy in IAM is `AWSLambda_FullAccess` and not `AWSLambdaFullAccess` but that might not matter

**Comment by nectarcode** [comment]
I tried tearing down dev and got the error `Unable to find ApiMapping with ID s2m9vd`

**Comment by nectarcode** [comment]
I tried deploying to a new stage, `test` and got the `Policy arn:aws:iam::aws:policy/AWSLambdaFullAccess does 
not exist or is not attachable. ` error again.

**Comment by nectarcode** [comment]
I tried adding a Role ARN in providers (which created a new CloudStack formation to create IAM Roles), instead of using the Access Key method, but when I tried deploying, I got `Role already exists` error

**Comment by jpgupta** [comment]
I'm getting the exact same issue, using the express component in what seems like an identical fashion to @nectarcode 

Deleted the role and now getting the AWSLambdaFullAccess does not exist

Tried deleting and creating a new provider but no avail

**Comment by nectarcode** [comment]
When I try to deploy with the debug flag, this is the output

```$ sls deploy --stage staging --debug
Initializing...
Action: "deploy" - Stage: "staging" - Org: "example" - App: "example-api" - Name: "example-api"
Deploying...
Deploying Express App...
Packaging Express.js application...
Unzipping /tmp/tf9rnhj/source.zip...
Files unzipped into /tmp/on27oel...
Installing Express + AWS Lambda handler...
Installing Serverless Framework SDK...
Zipping files...
Files zipped into /tmp/fc9by4.zip...
IAM Role not found.  Creating or updating a default role with the name: example-api-fc9by4-lambda-role
Creating or updating the meta IAM Role...

 EntityAlreadyExists: Role with name example-api-fc9by4-lambda-role already 
exists.

**Comment by nectarcode** [comment]
@jpgupta interesting that we are both experiencing this error for the first time at the same time...leads me to believe it could be an issue with an update that was made to the serverless components engine in the last 24 hours, because I made multiple deployments yesterday to multiple stages with no issues.

**Comment by calinbogdan** [comment]
> @jpgupta interesting that we are both experiencing this error for the first time at the same time...leads me to believe it could be an issue with an update that was made to the serverless components engine in the last 24 hours, because I made multiple deployments yesterday to multiple stages with no issues.

I'm also experiencing the same issue. Deployed this morning, no issues, but now it doesn't work anymore. I've deleted the service multiple times and I'm experiencing the same issue again and again.

**Comment by jpgupta** [comment]
@nectarcode / @calinbogdan - yep inclined to agree seems like a serverless issue! 

The project I was trying to deploy is a very simple Express API.. similarly no changes to our overall infrastructure and our other serverless services, which dont use components, are deploying fine fine

@nectarcode like you, the previous version of my API is still running which is a relief. I was planning on adding an endpoint to it today but have worked around that for now by deploying a separate serverless service, using API Gateway / Event endpoints rather than the express component and pointing things to that. 

Just going to hold on for an update from Serverless as I assume they'll be able to fix this relatively quickly!

**Comment by conversun** [comment]
Probably because of this
https://docs.aws.amazon.com/lambda/latest/dg/access-control-identity-based.html

**Comment by nectarcode** [comment]
@conversun Thanks so much for sharing that. Yes, it looks like serverless just needs to add an underscore.

https://docs.aws.amazon.com/lambda/latest/dg/security_iam_troubleshoot.html#security_iam_troubleshoot-admin-deprecation

`The AWSLambda_FullAccess policy grants full access to Lambda, Lambda console features, and other related AWS services. This policy was created by scoping down the previous policy AWSLambdaFullAccess. `

Hoping someone with an SLA agreement has this issue so it will get taken care of immediately. I have different stages but can’t deploy to any of them, so I’m thinking I will need a backup api I can point my domain to in case something like this happens again.

**Comment by eahefnawy** [comment]
Hey all, thanks for the heads up. Will publish a fix for this today.

**Comment by markvitapoly** [comment]
I was able to do a temp fix while we wait for the official one.

Here's what I did:
1. clone the express component: git clone https://github.com/serverless-components/express.git
2. modify src/util.js:38 to:   return 'arn:aws:iam::aws:policy/AWSLambda_FullAccess';
3. modify serverless.component.yml, change the org to your org and name to expressfix
4. in the express component folder, type: serverless publish --dev
5. tell your project to use the new component, serverless.yml, change component to:L expressfix@dev
6. sls deploy

There is a gotcha though, the new AWSLambda_FullAccess no longer gives you access to s3. So, if you are using s3, you'll need to add the s3 policy manually after deploying in the IAM manager.

I am curious what the official fix from @eahefnawy is though since amazon removing s3 from the policy will break backwards compatibility for those projects that expected it.

On a side now, I am not sure why I am not getting any logs in cloudwatch...

**Comment by eahefnawy** [comment]
Thanks for reporting and all your input! I've opened up a PR that fixes this here: (You can try it out now with `express@dev`)
https://github.com/serverless-components/express/pull/70



@markrawls I've looked into the new _FullAccess policy and it seems that it doesn't grant access to write logs, which is why I've switched to AWSLambdaBasicExecutionRole instead. For more permissions, folks could just use a custom role. You're right about it being a breaking change, which is why I'll be publishing v3.0.0 of the express component.

**Comment by mihaa1** [comment]
adding here (I'm working with aws sam but this thread helped me):
AWSLambdaFullAccess & AWSLambdaReadOnlyAccess are deprecated. See [here](https://docs.aws.amazon.com/lambda/latest/dg/security_iam_troubleshoot.html#security_iam_troubleshoot-admin-deprecation)

Switching to AWSLambda_FullAccess didn't work for me.
I had to add the policy manually: 
`{
    "Sid": "PermissionToInvoke",
    "Effect": "Allow",
    "Action": [
      "lambda:InvokeFunction"
    ],
    "Resource": "*"
}
`

**Comment by Raja0sama** [comment]
Hi, people by chance current issue and the below issue are because of the same reason?
```
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Creating Stack...
Serverless: Checking Stack create progress...
........
Serverless: Stack create finished...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service Project.zip file to S3 (21.21 MB)...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
.......................
Serverless: Operation failed!
Serverless: View the full error output: https://eu-west-2.console.aws.amazon.com/cloudformation/home?region=eu-west-2#/stack/detail?stackId=arn%3Aaws%3Acloudformation%3Aeu-west-2%3A915470643409%3Astack%2FProject-dev%2F8eeb91f0-90b7-11eb-8329-0232b5dbc2bc
 
 Serverless Error ----------------------------------------
 
  An error occurred: AppLambdaFunction - AccessDeniedExceptionnull (Service: AWSLambdaInternal; Status Code: 403; Error Code: AccessDeniedException; Request ID: 0dbac7f4-d22a-4974-afe8-d1c12654f6b4; Proxy: null).
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              14.15.5
     Framework Version:         2.29.0
     Plugin Version:            4.5.0
     SDK Version:               n/a
     Components Version:        3.7.3
 
```

I have been trying to deploy this express app for the past 2 days and unable to do it.

**Comment by jpgupta** [comment]
@Raja0sama I'm not the expert here but for what its worth, yes that looks like its the same issue, rel`ted to the AWSLambdaFullAccess policy not existing. Sounds like a fix is on the way!

**Comment by Raja0sama** [comment]
@jpgupta Okay thanks man, lets hope we can get the fix ASAP.

**Comment by eahefnawy** [comment]
The fix has been published 🚀

**Comment by Raja0sama** [comment]
> Hi, people by chance current issue and the below issue are because of the same reason?
> 
> ```
> Serverless: Packaging service...
> Serverless: Excluding development dependencies...
> Serverless: Creating Stack...
> Serverless: Checking Stack create progress...
> ........
> Serverless: Stack create finished...
> Serverless: Uploading CloudFormation file to S3...
> Serverless: Uploading artifacts...
> Serverless: Uploading service Project.zip file to S3 (21.21 MB)...
> Serverless: Validating template...
> Serverless: Updating Stack...
> Serverless: Checking Stack update progress...
> .......................
> Serverless: Operation failed!
> Serverless: View the full error output: https://eu-west-2.console.aws.amazon.com/cloudformation/home?region=eu-west-2#/stack/detail?stackId=arn%3Aaws%3Acloudformation%3Aeu-west-2%3A915470643409%3Astack%2FProject-dev%2F8eeb91f0-90b7-11eb-8329-0232b5dbc2bc
>  
>  Serverless Error ----------------------------------------
>  
>   An error occurred: AppLambdaFunction - AccessDeniedExceptionnull (Service: AWSLambdaInternal; Status Code: 403; Error Code: AccessDeniedException; Request ID: 0dbac7f4-d22a-4974-afe8-d1c12654f6b4; Proxy: null).
>  
>   Get Support --------------------------------------------
>      Docs:          docs.serverless.com
>      Bugs:          github.com/serverless/serverless/issues
>      Issues:        forum.serverless.com
>  
>   Your Environment Information ---------------------------
>      Operating System:          darwin
>      Node Version:              14.15.5
>      Framework Version:         2.29.0
>      Plugin Version:            4.5.0
>      SDK Version:               n/a
>      Components Version:        3.7.3
>  
> ```
> 
> I have been trying to deploy this express app for the past 2 days and unable to do it.
> then I tried to going with the serverless -express component approach and I end up getting the same error as above.
> 
> ```
> Action: "deploy" - Stage: "dev" - Org: "raja0sama" - App: "express-starter" - Name: "express-starter"
> 
> 43s › Serverless › Policy arn:aws:iam::aws:policy/AWSLambdaFullAccess does not exist or is not attachable. 
> 
>   Documentation: https://github.com/serverless/components 
> ```

@eahefnawy Fix is not working for the non-express-based components when we try to deploy it like below.
```
service: FindMeAContractor

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-2
  memorySize: 128
functions:
  app:
    handler: app.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

```

Tried with 
```
app: express-starter
component: express
name: express-starter

inputs:
  src: ./

```

Result : 
```
serverless ⚡framework
Action: "deploy" - Stage: "dev" - Org: "raja0sama" - App: "express-starter" - Name: "express-starter"

19s › Serverless › Cannot read property 'includes' of null 

  Documentation: https://github.com/serverless/components 
  Support: https://app.serverless.com/support 
  Slack: https://www.serverless.com/slack/ 
```

**Comment by abidCharlotte49er** [comment]
For Visual Studio / .NET folks 

In serverless.template file  I've replaced **AWSLambdaFullAccess** wtih **AWSLambda_FullAccess**
I have also tried to update template in CloudFormation. Not sure which one fixed it but I was able to publish again after doing those two things.

**Comment by Raja0sama** [comment]
@eahefnawy Worked for me as well, thanks, man.

**Comment by ashishmit14** [comment]
Worked for my issue as well.

**Comment by jastsai** [comment]
> adding here (I'm working with aws sam but this thread helped me):
> AWSLambdaFullAccess & AWSLambdaReadOnlyAccess are deprecated. See [here](https://docs.aws.amazon.com/lambda/latest/dg/security_iam_troubleshoot.html#security_iam_troubleshoot-admin-deprecation)
> 
> Switching to AWSLambda_FullAccess didn't work for me.
> I had to add the policy manually:
> `{ "Sid": "PermissionToInvoke", "Effect": "Allow", "Action": [ "lambda:InvokeFunction" ], "Resource": "*" } `

which role needs this policy? the deployment role or the role that attaches to the lambda?

**Comment by mdmjsh** [comment]
Is anyone else still experiencing this issue? I'm running my deployments in Travis and from today this issue is occurring. 

Here's the output from my build:
```
30.76s$ npm install -g serverless
install.2
0.72s$ serverless --version
Framework Core: 2.32.1
Plugin: 4.5.3
SDK: 4.2.2
Components: 3.8.1
....
 Serverless Error ----------------------------------------
 
  An error occurred: CodeDeployServiceRole - Policy arn:aws:iam::aws:policy/AWSLambdaFullAccess does not exist or is not attachable. (Service: AmazonIdentityManagement; Status Code: 404; Error Code: NoSuchEntity; Request ID: 489038b4-7d87-4b5b-b064-287fd476bfb5; Proxy: null).
```

Any help here would be appreciated!

**Comment by jastsai** [comment]
> Is anyone else still experiencing this issue? I'm running my deployments in Travis and from today this issue is occurring.
> 
> Here's the output from my build:
> 
> ```
> 30.76s$ npm install -g serverless
> install.2
> 0.72s$ serverless --version
> Framework Core: 2.32.1
> Plugin: 4.5.3
> SDK: 4.2.2
> Components: 3.8.1
> ....
>  Serverless Error ----------------------------------------
>  
>   An error occurred: CodeDeployServiceRole - Policy arn:aws:iam::aws:policy/AWSLambdaFullAccess does not exist or is not attachable. (Service: AmazonIdentityManagement; Status Code: 404; Error Code: NoSuchEntity; Request ID: 489038b4-7d87-4b5b-b064-287fd476bfb5; Proxy: null).
> ```
> 
> Any help here would be appreciated!

In my case, I was using a plugin that uses this role AWSLambdaFullAccess. I was able to override the default role used by the plugin and  the issue goes away.

**Comment by mdmjsh** [comment]
> In my case, I was using a plugin that uses this role AWSLambdaFullAccess. I was able to override the default role used by the plugin and the issue goes away.

 @jastsai thanks for the steer, that seemed to be it for me as I disabled the plugin as a test and the deployment succeeded. I'm unaware of how to manage the default role for the plugin, for posterity, if you have any resources that helped you here could you share the link please? :)

**Comment by jastsai** [comment]
the plugin that I used it called:
https://github.com/davidgf/serverless-plugin-canary-deployments
It supports the default codeDeploy role override.
```
Default configurations

You can set default values for all functions in a top-level custom
deploymentSettings section. E.g.:

custom:
  deploymentSettings:
    codeDeployRole: some_arn_value
    codeDeployRolePermissionsBoundary: some_arn_value
    stages:
      - dev
      - prod
functions:
  ...

```

I also raised a issue in the repo and the author fixed it yesterday.

I was able to find "AWSLambdaFullAccess" in his repo but now it is
fixed. You may try to find it in your plugin repo and also contact the
author to fix it.



Thanks,
Jason Tsai

**Comment by alisalahio** [comment]
The issue still occurs to me using the [aws-lambda component](https://github.com/serverless-components/aws-lambda)

**Comment by jastsai** [comment]
> The issue still occurs to me using the [aws-lambda component](https://github.com/serverless-components/aws-lambda)
ya I see it is used in https://github.com/serverless-components/aws-lambda/blob/master/src/utils.js

**Comment by eahefnawy** [comment]
This is now fixed in the aws-lambda component as well.
